server:
  port: 6969
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project-shop-sys?serverTimezone=Asia/Seoul
    username: root
    password: oracle

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

logging:
  level:
    com.tutorial: debug

jwt:
  #header: Authorization
  secret: and0LWtleS1mb3Itd2lsbG1zLXByb2plY3Qtc2hvcC1zeXMtbGV0cy1tYWtlLWEtZnVja2luZy1wb3J0Zm9saW8=

#https://www.jstoolset.com/base64-encode
#?? jwt? ??? secret key? HS512 ????? ??? ??? ??? 512bit, ? 64byte ??? secret key? ???? ??.
#??? ?? ???? Base64 ? ???? ?? ????.
#